### ISSUE TITLE
Feature: use Azure Pipelines for building

### ISSUE THREAD

**Issue by StefH** [StefH/System.Linq.Dynamic.Core#209]
https://github.com/StefH/System.Linq.Dynamic.Core/pull/210

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any suggestions or questions. I'm happy to help!

**Comment by StefH** [comment]
@kaylangan
Thanks for your help.

My plan was to implement the same steps as I did on https://github.com/WireMock-Net/WireMock.Net/tree/Response_BodyData

For this project this means
- remove appveyor CI
- add .yml file and make sure that tests run
- integrate sonarcloud
- publish to myget

Do you maybe have some hints or tips when integrating with Azure Pipelines?

**Comment by StefH** [comment]
Some questions:

- can you tell me step by step how to make the build public?
- how to define multiple projects to build? I also asked that here https://github.com/Im5tu/im5tu-hugo/issues/1
- it seems that I cannot build net3.5 and uap10.0  with dotnet build? Or should I use msbuild with some workarounds?

**Comment by kaylangan** [comment]
> * can you tell me step by step how to make the build public?

Check out the docs on [making a private project public](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public?view=vsts&tabs=new-nav#make-a-private-project-public).

> * how to define multiple projects to build? I also asked that here [Im5tu/im5tu-hugo#1](https://github.com/Im5tu/im5tu-hugo/issues/1)

You can [use wildcards as you've done it here](https://github.com/WireMock-Net/WireMock.Net/blob/Response_BodyData/azure-pipelines.yml#L7). We have a doc on more [advanced file name patterns](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=vsts). Would this meet your needs?

> * it seems that I cannot build net3.5 and uap10.0  with dotnet build? Or should I use msbuild with some workarounds?

What's the error that you are getting? If you can get MSBuild to work, that's great. Otherwise, I'll have to check with one of my teammates.

**Comment by StefH** [comment]
@kaylangan 
1. This does not work for me because my project / sourcecode is from GitHub. I only use the devops pipelines in Azure to build.

2. I solved it like:
``` yaml
variables:
  buildProjects: '**/src/**/+(System.Linq.Dynamic.Core|EntityFramework.DynamicLinq|Microsoft.EntityFrameworkCore.DynamicLinq).csproj'
```

3. I used a workaround to just excluded these two frameworks from the CI - build on Azure Pipelines like:
``` xml
<PropertyGroup Condition=" '$(buildType)' == 'azure-pipelines-ci' ">
    <TargetFrameworks>net40;net45;net46;netstandard1.3;netstandard2.0</TargetFrameworks>
</PropertyGroup> 
```

**Comment by StefH** [comment]
3. Error message is like:
```
C:\Users\Stef\Documents\Github\System.Linq.Dynamic.Core\src\System.Linq.Dynamic.Core\System.Linq.Dynamic.Core.csproj : error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.
C:\Users\Stef\Documents\Github\System.Linq.Dynamic.Core\src\Microsoft.EntityFrameworkCore.DynamicLinq\Microsoft.EntityFrameworkCore.DynamicLinq.csproj : error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.
```

**Comment by kaylangan** [comment]
Azure DevOps projects include source control and pipelines so those steps should work to make your builds public. The reason I think your Azure Pipelines project is set to private is when I click to see the build results I get 401'd instead of seeing the [logs](https://stef.visualstudio.com/3a814af6-1684-425a-b7e8-f1794ca3f840/_build/results?buildId=371).

**Comment by StefH** [comment]
Hello @kaylangan 
I created a simple test project which shows the error when building `net 3.5` (https://github.com/StefH/AzurePipelinesTest3/issues/2)

This PR fails:
https://github.com/StefH/AzurePipelinesTest3/pull/1
