### ISSUE TITLE
Querying a list of ExpandoObjects

### ISSUE THREAD

**Issue by FransVanEk** [StefH/System.Linq.Dynamic.Core#305]
I have a list of ExpandoObjects that i want to query.  These are dynamically formed and have no typed counterpart. 

The linqquery will look something like this :  Text=="demo"

the object has a property 
``` c#
private List<object> ConvertFilteredPropertyToListItems(string propertyName, object dataObject, string indexerValue)
{
  var result = new List<Object>();
  var linqQuery = RemoveFilterBrackets(indexerValue);

  foreach (var item in ((List<ExpandoObject>)GetPropertyValueFor(propertyName, dataObject)).AsQueryable().Where(linqQuery))
  {
    result.Add(item);
  }
  return result;
}
```

The error I get is:  
  **Message=No property or field 'Text' exists in type 'ExpandoObject'**
although this property does exists... 

My question is: should it be possible to quesry an expandoobject like this? and if so what do i need to change? 

kind regards,

Frans

**Comment by StefH** [comment]
I think this is not possible because the properties are *lost* in an ExpandoObject.
See this unit test: https://github.com/StefH/System.Linq.Dynamic.Core/blob/dd4a659ff89550ed502e15f70d421e7144c11c76/test/System.Linq.Dynamic.Core.Tests/ExpressionTests.cs#L1429


If possible, use`JObject`, that works.
https://github.com/StefH/System.Linq.Dynamic.Core/blob/a963fcb7385d25e3e29cebf6e5049c295ace6145/test/System.Linq.Dynamic.Core.Tests/QueryableTests.Cast.cs

**Comment by FransVanEk** [comment]
OK thanks, i assume this is not on the roadmap for the near future..  I will refactor the solution to use the JObject...  thanks for the quick response.
